name: CI/CD Pipeline

on:
  push:
    branches:
      - development
    paths:
      - 'django-app/**'
      - 'fastapi-app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'django-app/**'
      - 'fastapi-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 061039781993.dkr.ecr.us-east-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push FastAPI image
        run: |
          cd fastapi-app
          docker build -t fastapi-app .
          IMAGE_TAG=${{ github.ref_name }}
          # Remove qualquer caractere inválido da tag
          IMAGE_TAG=$(echo "$IMAGE_TAG" | sed 's/[^a-zA-Z0-9._-]/_/g')
          docker tag fastapi-app:latest 061039781993.dkr.ecr.us-east-2.amazonaws.com/fastapi-app:$IMAGE_TAG
          docker push 061039781993.dkr.ecr.us-east-2.amazonaws.com/fastapi-app:$IMAGE_TAG
          
      - name: Build and push Django image
        run: |
          cd django-app
          docker build -t django-app .
          IMAGE_TAG=${{ github.ref_name }}
          # Remove qualquer caractere inválido da tag
          IMAGE_TAG=$(echo "$IMAGE_TAG" | sed 's/[^a-zA-Z0-9._-]/_/g')
          docker tag django-app:latest 061039781993.dkr.ecr.us-east-2.amazonaws.com/django-app:$IMAGE_TAG
          docker push 061039781993.dkr.ecr.us-east-2.amazonaws.com/django-app:$IMAGE_TAG
        

          - name: Deploy FastAPI service to ECS
          if: github.ref == 'refs/heads/development'
          run: |
            aws ecs update-service --cluster development-cluster --service fastapi-service-development --force-new-deployment --region us-east-2
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Deploy Django service to ECS
        if: github.ref == 'refs/heads/development'
        run: |
          aws ecs update-service --cluster development-cluster --service django-service-development --force-new-deployment --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Deploy FastAPI service to ECS
        if: github.ref == 'refs/heads/main'
        run: |
          aws ecs update-service --cluster production-cluster --service fastapi-service-production --force-new-deployment --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Deploy Django service to ECS
        if: github.ref == 'refs/heads/main'
        run: |
          aws ecs update-service --cluster production-cluster --service django-service-production --force-new-deployment --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
